title: LIM 文档中心
description: 局域网即时通讯协议(LAN Instant Messaging)
show_downloads: false
###########################################################################################
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
